name: ajay_portfolio_workspace
description: Ajay's Portfolio Website

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  flutter_lints: ^5.0.0
  melos: ^6.3.2

flutter:
  uses-material-design: true
