name: my_site
description: All links for Ajay and more
publish_to: 'none'
version: 1.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^10.2.0
  url_launcher: ^6.1.14
  any_link_preview: ^3.0.1
  animated_text_kit: ^4.2.2
  google_fonts: ^6.0.0
  flutter_animate: ^4.2.0+1
  im_animations: ^0.1.2
  animate_it: ^0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/


