name: ajay_portfolio
description: Ajay's Portfolio Website
version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  url_launcher: ^6.3.1
  any_link_preview: ^3.0.3
  animated_text_kit: ^4.2.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  im_animations: ^0.1.2
  animate_it: ^0.0.1+2
  animate_on_hover: ^1.0.2
  package_info_plus: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/


