name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Manual version override (optional)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine version
        id: set_version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | sed "s/+.*//")
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/${{ steps.set_version.outputs.version }}/"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: web-build

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Set up version directory
        run: |
          VERSION="${{ needs.build.outputs.version }}"
          mkdir -p gh-pages/$VERSION

      - name: Copy build files
        run: |
          VERSION="${{ needs.build.outputs.version }}"
          cp -R web-build/* gh-pages/$VERSION/

      - name: Commit and push changes
        working-directory: gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy version ${{ needs.build.outputs.version }}"
          git push