name: Flutter Web Deploy with Melos

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (optional - will use package version if not provided)'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for version extraction

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true

      - name: Setup Melos
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: Extract version from portfolio package
        id: get_version
        if: github.event.inputs.version == ''
        run: |
          cd apps/ajay_portfolio
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted from ajay_portfolio package: $VERSION"

      - name: Set manual version
        if: github.event.inputs.version != ''
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "Using manually provided version: ${{ github.event.inputs.version }}"

      - name: Run tests
        run: melos run test

      - name: Run lint
        run: melos run lint

      - name: Build Flutter Web
        run: |
          cd apps/ajay_portfolio
          flutter build web --release --base-href "/${{ env.VERSION }}/"

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p tmp
          cd tmp
          
          # Clone gh-pages branch
          git clone --single-branch --branch gh-pages "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
          cd gh-pages
          
          # Create version directory and copy new build
          mkdir -p "${{ env.VERSION }}"
          cp -r ../../apps/ajay_portfolio/build/web/* "${{ env.VERSION }}/"
          
          # Create or update version list with timestamps
          echo "# Available Versions" > versions.md
          echo "" >> versions.md
          echo "| Version | Deployment Date |" >> versions.md
          echo "|---------|-----------------|" >> versions.md
          for d in */ ; do
            if [[ "$d" =~ ^[0-9]+\.[0-9]+\.[0-9]+/$ ]]; then
              version="${d%/}"
              date=$(git log -1 --format="%ad" --date=short -- "$d")
              echo "| [$version]($version/) | $date |" >> versions.md
            fi
          done
          
          # Stage, commit and push
          git add .
          git commit -m "Deploy version ${{ env.VERSION }}"
          git push

      - name: Create deployment summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ Successfully deployed version ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "📱 Access your app at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.VERSION }}/" >> $GITHUB_STEP_SUMMARY
          echo "📋 View all versions at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/versions.md" >> $GITHUB_STEP_SUMMARY